[build]
  command = "npm run build"
  publish = "dist/tools/task-smasher"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  autoLaunch = true
  framework = "vite"

# Enable Netlify Blob store for persistent rate limiting
[blobs]
  serve_folder = "public"

# SPA fallback for TaskSmasher app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects for serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SEO-Friendly URL Overrides
[[redirects]]
  from = "/daily-organizer/*"
  to = "/daily-organizer/index.html"
  status = 200

[[redirects]]
  from = "/goal-planner/*"
  to = "/goal-planner/index.html"
  status = 200

[[redirects]]
  from = "/marketing-tasks/*"
  to = "/marketing-tasks/index.html"
  status = 200

[[redirects]]
  from = "/recipe-steps/*"
  to = "/recipe-steps/index.html"
  status = 200

[[redirects]]
  from = "/home-chores/*"
  to = "/home-chores/index.html"
  status = 200

[[redirects]]
  from = "/freelancer-projects/*"
  to = "/freelancer-projects/index.html"
  status = 200

[[redirects]]
  from = "/trip-planner/*"
  to = "/trip-planner/index.html"
  status = 200

[[redirects]]
  from = "/shopping-tasks/*"
  to = "/shopping-tasks/index.html"
  status = 200

[[redirects]]
  from = "/study-plan/*"
  to = "/study-plan/index.html"
  status = 200

[[redirects]]
  from = "/event-planning/*"
  to = "/event-planning/index.html"
  status = 200

[[redirects]]
  from = "/diy-projects/*"
  to = "/diy-projects/index.html"
  status = 200

[[redirects]]
  from = "/creative-projects/*"
  to = "/creative-projects/index.html"
  status = 200

# Catch-all redirect for SPA - must be at the very bottom
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200