[build]
  command = "npm run build"
  publish = "dist/tools/task-smasher"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  autoLaunch = true
  framework = "vite"

# Enable Netlify Blob store for persistent rate limiting
[blobs]
  serve_folder = "public"

# SPA fallback for TaskSmasher app
[[redirects]]
  from = "/tools/task-smasher/*"
  to = "/tools/task-smasher/index.html"
  status = 200

# API redirects for serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SEO-Friendly URL Overrides
[[redirects]]
  from = "/tools/task-smasher/daily-organizer/*"
  to = "/tools/task-smasher/daily-organizer/index.html"
  status = 200

[[redirects]]
  from = "/tools/task-smasher/goal-planner/*"
  to = "/tools/task-smasher/goal-planner/index.html"
  status = 200

[[redirects]]
  from = "/tools/task-smasher/marketing-tasks/*"
  to = "/tools/task-smasher/marketing-tasks/index.html"
  status = 200

[[redirects]]
  from = "/tools/task-smasher/recipe-steps/*"
  to = "/tools/task-smasher/recipe-steps/index.html"
  status = 200

[[redirects]]
  from = "/tools/task-smasher/home-chores/*"
  to = "/tools/task-smasher/home-chores/index.html"
  status = 200

[[redirects]]
  from = "/tools/task-smasher/freelancer-projects/*"
  to = "/tools/task-smasher/freelancer-projects/index.html"
  status = 200

[[redirects]]
  from = "/tools/task-smasher/trip-planner/*"
  to = "/tools/task-smasher/trip-planner/index.html"
  status = 200

[[redirects]]
  from = "/tools/task-smasher/shopping-tasks/*"
  to = "/tools/task-smasher/shopping-tasks/index.html"
  status = 200

[[redirects]]
  from = "/tools/task-smasher/study-plan/*"
  to = "/tools/task-smasher/study-plan/index.html"
  status = 200

[[redirects]]
  from = "/tools/task-smasher/event-planning/*"
  to = "/tools/task-smasher/event-planning/index.html"
  status = 200

[[redirects]]
  from = "/tools/task-smasher/diy-projects/*"
  to = "/tools/task-smasher/diy-projects/index.html"
  status = 200

[[redirects]]
  from = "/tools/task-smasher/creative-projects/*"
  to = "/tools/task-smasher/creative-projects/index.html"
  status = 200

# Catch-all redirect for SPA - must be at the very bottom
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200